# .github/workflows/python-ci.yml
name: Python CI without specific test file

on:
  push:
    branches: [main, UAT-BRANCH]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests with retry logic
        run: |
          retry=0
          until [ $retry -ge 3 ]
          do
            echo "🧪 Running tests... attempt $((retry+1



